# Use Node.js v14
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install dependencies
RUN npm install --save @sendgrid/mail
RUN npm install

# If you are building for production, you can use:
# RUN npm ci --only=production

# Bundle app source
COPY . .

# Build the JavaScript files (if needed)
RUN npm run build:js

# Expose the port
EXPOSE 4100

# Set environment variables
ENV NODE_ENV=production

# Run the application
CMD [ "npm", "start" ]
